proxy:
  image: traefik
  command: --web --docker --logLevel=INFO
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

web:
  image: 'firstandthird/node:8.9-2-dev'
  volumes:
    - './:/home/app/src'
  environment:
    PORT: 8080
    FORCE_COLOR: 1
    ENDPOINT: 
  ports:
    - '8080'
  links:
    - 'proxy:proxy'
  labels:
    - "traefik.frontend.rule=PathPrefix:/"

