userAgentSkip:
  - 'Slackbot'
redirectCount: '{{ ENV.REDIRECT_COUNT || 10 }}'
plugins:
  hapi-req:
  hapi-favicon:
  hapi-robots:
    envs:
      production:
        '*': '/'
  hapi-oppsy:
    _enabled: false
